apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    name: php-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: php-app-pod
    app: demo-voting-app
